"""initial schema

Revision ID: 7131d874cdd2
Revises: 0001_extensions
Create Date: 2026-09-27 14:09:45.684132
"""

from __future__ import annotations

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "7131d874cdd2"
down_revision: str | None = "0001_extensions"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organization",
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "app_user",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=160), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "ADMIN", "PRICING_MANAGER", "ANALYST", name="userrole", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organization.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "email", name="uq_user_org_email"),
    )
    op.create_index(op.f("ix_app_user_email"), "app_user", ["email"], unique=False)
    op.create_table(
        "category",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organization.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["parent_id"], ["category.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "slug", name="uq_category_org_slug"),
    )
    op.create_table(
        "competitor",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column("domain", sa.String(length=255), nullable=False),
        sa.Column(
            "connector_type",
            sa.Enum("SYNTHETIC", "CSV", "HTTP", name="connectortype", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("connector_config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_crawled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organization.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "slug", name="uq_competitor_org_slug"),
    )
    op.create_table(
        "financial_period",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("label", sa.String(length=40), nullable=False),
        sa.Column("granularity", sa.String(length=16), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("source", sa.String(length=40), nullable=False),
        sa.Column("source_filename", sa.String(length=255), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organization.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "label", name="uq_financial_period_label"),
    )
    op.create_index(
        "ix_financial_period_org_start",
        "financial_period",
        ["organization_id", "period_start"],
        unique=False,
    )
    op.create_table(
        "model_run",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "ELASTICITY", "FORECAST", "ANOMALY", name="modelkind", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column("label", sa.String(length=160), nullable=False),
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("artifact_path", sa.String(length=512), nullable=True),
        sa.Column("n_products", sa.Integer(), nullable=False),
        sa.Column("train_start", sa.Date(), nullable=True),
        sa.Column("train_end", sa.Date(), nullable=True),
        sa.Column("is_champion", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organization.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_model_run_kind_created", "model_run", ["kind", "created_at"], unique=False)
    op.create_table(
        "advisor_report",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("period_id", sa.UUID(), nullable=True),
        sa.Column("model_name", sa.String(length=120), nullable=False),
        sa.Column("facts", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("narrative", sa.Text(), nullable=False),
        sa.Column("recommendations", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("grounding_passed", sa.Boolean(), nullable=False),
        sa.Column("grounding_violations", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organization.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["period_id"], ["financial_period.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_advisor_org_created", "advisor_report", ["organization_id", "created_at"], unique=False
    )
    op.create_table(
        "audit_event",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("actor_user_id", sa.UUID(), nullable=True),
        sa.Column("actor_label", sa.String(length=160), nullable=False),
        sa.Column(
            "action",
            sa.Enum(
                "CREATE",
                "UPDATE",
                "DELETE",
                "APPROVE",
                "REJECT",
                "APPLY",
                "INGEST",
                "TRAIN",
                "SIMULATE",
                "LOGIN",
                name="auditaction",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("entity_type", sa.String(length=80), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["actor_user_id"], ["app_user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["organization_id"], ["organization.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_audit_entity", "audit_event", ["entity_type", "entity_id"], unique=False)
    op.create_index(
        "ix_audit_org_created", "audit_event", ["organization_id", "created_at"], unique=False
    )
    op.create_table(
        "financial_finding",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("period_id", sa.UUID(), nullable=False),
        sa.Column("metric_key", sa.String(length=64), nullable=False),
        sa.Column("detector", sa.String(length=40), nullable=False),
        sa.Column(
            "severity",
            sa.Enum(
                "INFO", "WARNING", "CRITICAL", name="alertseverity", native_enum=False, length=20
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("detail", sa.Text(), nullable=False),
        sa.Column("current_value", sa.Float(), nullable=True),
        sa.Column("expected_value", sa.Float(), nullable=True),
        sa.Column("delta_pct", sa.Float(), nullable=True),
        sa.Column("z_score", sa.Float(), nullable=True),
        sa.Column("context", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organization.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["period_id"], ["financial_period.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_finding_period_severity", "financial_finding", ["period_id", "severity"], unique=False
    )
    op.create_table(
        "financial_line_item",
        sa.Column("period_id", sa.UUID(), nullable=False),
        sa.Column(
            "statement_type",
            sa.Enum(
                "INCOME_STATEMENT",
                "BALANCE_SHEET",
                "CASH_FLOW",
                "OPERATING_KPI",
                name="statementtype",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("canonical_key", sa.String(length=64), nullable=False),
        sa.Column("source_label", sa.String(length=160), nullable=False),
        sa.Column("amount", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["period_id"], ["financial_period.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("period_id", "canonical_key", name="uq_line_item_period_key"),
    )
    op.create_index(
        "ix_line_item_statement",
        "financial_line_item",
        ["period_id", "statement_type"],
        unique=False,
    )
    op.create_table(
        "financial_metric",
        sa.Column("period_id", sa.UUID(), nullable=False),
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("label", sa.String(length=120), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("unit", sa.String(length=16), nullable=False),
        sa.Column("formula", sa.String(length=255), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["period_id"], ["financial_period.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("period_id", "key", name="uq_metric_period_key"),
    )
    op.create_table(
        "product",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("category_id", sa.UUID(), nullable=True),
        sa.Column("sku", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("brand", sa.String(length=120), nullable=False),
        sa.Column("gtin", sa.String(length=20), nullable=True),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("attributes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("current_price", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("unit_cost", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("msrp", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("min_margin_pct", sa.Numeric(precision=8, scale=6), nullable=False),
        sa.Column("max_price_step_pct", sa.Numeric(precision=8, scale=6), nullable=False),
        sa.Column("price_floor_override", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("price_ceiling_override", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("map_price", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE",
                "DISCONTINUED",
                "END_OF_LIFE",
                name="productstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("launch_date", sa.Date(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("current_price > 0", name="ck_product_current_price"),
        sa.CheckConstraint(
            "min_margin_pct >= 0 AND min_margin_pct < 1", name="ck_product_min_margin"
        ),
        sa.CheckConstraint("unit_cost >= 0", name="ck_product_unit_cost"),
        sa.ForeignKeyConstraint(["category_id"], ["category.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["organization_id"], ["organization.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "sku", name="uq_product_org_sku"),
    )
    op.create_index(op.f("ix_product_gtin"), "product", ["gtin"], unique=False)
    op.create_index(
        "ix_product_org_category", "product", ["organization_id", "category_id"], unique=False
    )
    op.create_index(op.f("ix_product_sku"), "product", ["sku"], unique=False)
    op.create_table(
        "simulation_run",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("horizon_days", sa.Integer(), nullable=False),
        sa.Column("scenario", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("results", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("n_monte_carlo", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["created_by_id"], ["app_user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["organization_id"], ["organization.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_simulation_org_created",
        "simulation_run",
        ["organization_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "alert",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "alert_type",
            sa.Enum(
                "COMPETITOR_STOCKOUT",
                "COMPETITOR_RESTOCK",
                "PRICE_UNDERCUT",
                "MARGIN_BREACH",
                "DATA_STALE",
                "FINANCIAL_ANOMALY",
                name="alerttype",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column(
            "severity",
            sa.Enum(
                "INFO", "WARNING", "CRITICAL", name="alertseverity", native_enum=False, length=20
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "OPEN", "ACKNOWLEDGED", "RESOLVED", name="alertstatus", native_enum=False, length=20
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=True),
        sa.Column("competitor_id", sa.UUID(), nullable=True),
        sa.Column("context", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("dedupe_key", sa.String(length=255), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["competitor_id"], ["competitor.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["organization_id"], ["organization.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["product_id"], ["product.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_alert_dedupe_key"), "alert", ["dedupe_key"], unique=False)
    op.create_index(
        "ix_alert_org_status_created",
        "alert",
        ["organization_id", "status", "created_at"],
        unique=False,
    )
    op.create_table(
        "competitor_listing",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("competitor_id", sa.UUID(), nullable=False),
        sa.Column("external_id", sa.String(length=128), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("brand", sa.String(length=120), nullable=False),
        sa.Column("gtin", sa.String(length=20), nullable=True),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("url", sa.String(length=1024), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
        sa.Column("matched_product_id", sa.UUID(), nullable=True),
        sa.Column("match_confidence", sa.Float(), nullable=True),
        sa.Column(
            "match_method",
            sa.Enum(
                "GTIN",
                "EMBEDDING",
                "MANUAL",
                "UNMATCHED",
                name="matchmethod",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "match_status",
            sa.Enum(
                "PENDING",
                "AUTO_ACCEPTED",
                "CONFIRMED",
                "REJECTED",
                "NEEDS_REVIEW",
                name="matchstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("match_explanation", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["competitor_id"], ["competitor.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["matched_product_id"], ["product.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["organization_id"], ["organization.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("competitor_id", "external_id", name="uq_listing_competitor_external"),
    )
    op.create_index(
        op.f("ix_competitor_listing_gtin"), "competitor_listing", ["gtin"], unique=False
    )
    op.create_index("ix_listing_match_status", "competitor_listing", ["match_status"], unique=False)
    op.create_index(
        "ix_listing_matched_product", "competitor_listing", ["matched_product_id"], unique=False
    )
    op.create_table(
        "cost_history",
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("unit_cost", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("note", sa.String(length=255), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["product_id"], ["product.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("product_id", "valid_from", name="uq_cost_product_date"),
    )
    op.create_index(
        "ix_cost_history_product_date", "cost_history", ["product_id", "valid_from"], unique=False
    )
    op.create_table(
        "cross_elasticity",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("related_product_id", sa.UUID(), nullable=False),
        sa.Column("model_run_id", sa.UUID(), nullable=False),
        sa.Column("elasticity", sa.Float(), nullable=False),
        sa.Column("std_error", sa.Float(), nullable=True),
        sa.Column("p_value", sa.Float(), nullable=True),
        sa.Column("is_significant", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("product_id <> related_product_id", name="ck_cross_distinct"),
        sa.ForeignKeyConstraint(["model_run_id"], ["model_run.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["organization_id"], ["organization.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["product_id"], ["product.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["related_product_id"], ["product.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "product_id", "related_product_id", "model_run_id", name="uq_cross_pair_run"
        ),
    )
    op.create_table(
        "elasticity_estimate",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("model_run_id", sa.UUID(), nullable=False),
        sa.Column(
            "method",
            sa.Enum(
                "LOG_LOG_OLS",
                "POOLED_CATEGORY",
                "PRIOR_FALLBACK",
                name="elasticitymethod",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("elasticity", sa.Float(), nullable=False),
        sa.Column("std_error", sa.Float(), nullable=True),
        sa.Column("ci_low", sa.Float(), nullable=True),
        sa.Column("ci_high", sa.Float(), nullable=True),
        sa.Column("p_value", sa.Float(), nullable=True),
        sa.Column("r_squared", sa.Float(), nullable=True),
        sa.Column("n_observations", sa.Integer(), nullable=False),
        sa.Column("price_variation_cv", sa.Float(), nullable=True),
        sa.Column("intercept", sa.Float(), nullable=True),
        sa.Column("reference_price", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("coefficients", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("diagnostics", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("is_reliable", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["model_run_id"], ["model_run.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["organization_id"], ["organization.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["product_id"], ["product.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("product_id", "model_run_id", name="uq_elasticity_product_run"),
    )
    op.create_index(
        "ix_elasticity_product_created",
        "elasticity_estimate",
        ["product_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "forecast_point",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("model_run_id", sa.UUID(), nullable=False),
        sa.Column("target_date", sa.Date(), nullable=False),
        sa.Column("predicted_units", sa.Float(), nullable=False),
        sa.Column("lower_units", sa.Float(), nullable=True),
        sa.Column("upper_units", sa.Float(), nullable=True),
        sa.Column("assumed_price", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["model_run_id"], ["model_run.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["organization_id"], ["organization.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["product_id"], ["product.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("model_run_id", "product_id", "target_date", name="uq_forecast_point"),
    )
    op.create_index(
        "ix_forecast_product_date", "forecast_point", ["product_id", "target_date"], unique=False
    )
    op.create_table(
        "ground_truth",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("generator_version", sa.String(length=20), nullable=False),
        sa.Column("seed", sa.BigInteger(), nullable=False),
        sa.Column("own_elasticity", sa.Float(), nullable=False),
        sa.Column("competitor_cross_elasticity", sa.Float(), nullable=False),
        sa.Column("base_demand", sa.Float(), nullable=False),
        sa.Column("reference_price", sa.Float(), nullable=False),
        sa.Column("promo_lift", sa.Float(), nullable=False),
        sa.Column("trend_per_year", sa.Float(), nullable=False),
        sa.Column("seasonal_amplitude", sa.Float(), nullable=False),
        sa.Column("noise_sigma", sa.Float(), nullable=False),
        sa.Column(
            "sibling_cross_elasticities", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organization.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["product_id"], ["product.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("product_id", name="uq_ground_truth_product"),
    )
    op.create_table(
        "price_recommendation",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("model_run_id", sa.UUID(), nullable=True),
        sa.Column(
            "objective",
            sa.Enum(
                "REVENUE",
                "MARGIN",
                "PENETRATION",
                name="pricingobjective",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("current_price", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("recommended_price", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("unconstrained_price", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("price_floor", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("price_ceiling", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("expected_units", sa.Float(), nullable=True),
        sa.Column("expected_revenue", sa.Float(), nullable=True),
        sa.Column("expected_margin", sa.Float(), nullable=True),
        sa.Column("baseline_revenue", sa.Float(), nullable=True),
        sa.Column("baseline_margin", sa.Float(), nullable=True),
        sa.Column("elasticity_used", sa.Float(), nullable=True),
        sa.Column("elasticity_ci_low", sa.Float(), nullable=True),
        sa.Column("elasticity_ci_high", sa.Float(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("binding_constraints", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("rationale", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PROPOSED",
                "APPROVED",
                "REJECTED",
                "APPLIED",
                "EXPIRED",
                name="recommendationstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("decided_by_id", sa.UUID(), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decision_note", sa.Text(), nullable=False),
        sa.Column("valid_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("recommended_price > 0", name="ck_recommendation_price"),
        sa.ForeignKeyConstraint(["decided_by_id"], ["app_user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["model_run_id"], ["model_run.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["organization_id"], ["organization.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["product_id"], ["product.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_recommendation_org_status",
        "price_recommendation",
        ["organization_id", "status", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_recommendation_product_created",
        "price_recommendation",
        ["product_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "sales_fact",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("sale_date", sa.Date(), nullable=False),
        sa.Column("channel", sa.String(length=40), nullable=False),
        sa.Column("units", sa.Integer(), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("unit_cost", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("promo_flag", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint("units >= 0", name="ck_sales_units"),
        sa.ForeignKeyConstraint(["organization_id"], ["organization.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["product_id"], ["product.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "product_id", "sale_date", "channel", name="uq_sales_product_date_channel"
        ),
    )
    op.create_index(
        "ix_sales_fact_org_date", "sales_fact", ["organization_id", "sale_date"], unique=False
    )
    op.create_index(
        "ix_sales_fact_product_date", "sales_fact", ["product_id", "sale_date"], unique=False
    )
    op.create_table(
        "match_candidate",
        sa.Column("listing_id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("vector_score", sa.Float(), nullable=False),
        sa.Column("fuzzy_score", sa.Float(), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["listing_id"], ["competitor_listing.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["product_id"], ["product.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("listing_id", "product_id", name="uq_candidate_listing_product"),
    )
    op.create_index(
        "ix_match_candidate_listing_score", "match_candidate", ["listing_id", "score"], unique=False
    )
    op.create_table(
        "price_observation",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("listing_id", sa.UUID(), nullable=False),
        sa.Column(
            "observed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("price", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("shipping_cost", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column(
            "stock_state",
            sa.Enum(
                "IN_STOCK",
                "OUT_OF_STOCK",
                "UNKNOWN",
                name="stockstate",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("promo_flag", sa.Boolean(), nullable=False),
        sa.Column("is_outlier", sa.Boolean(), nullable=False),
        sa.Column("raw_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint("price > 0", name="ck_observation_price"),
        sa.ForeignKeyConstraint(["listing_id"], ["competitor_listing.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["organization_id"], ["organization.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_observation_listing_time",
        "price_observation",
        ["listing_id", "observed_at"],
        unique=False,
    )
    op.create_index(
        "ix_observation_org_time",
        "price_observation",
        ["organization_id", "observed_at"],
        unique=False,
    )
    # ### end Alembic commands ###

    # -- hand-written additions (Alembic cannot autogenerate these) ----------
    # HNSW index for approximate nearest-neighbour product matching (Module A).
    # Cosine distance matches the normalized embeddings produced by app.matching.
    op.execute(
        "CREATE INDEX ix_listing_embedding_hnsw ON competitor_listing "
        "USING hnsw (embedding vector_cosine_ops)"
    )
    # Trigram index to accelerate fuzzy title pre-filtering / manual search.
    op.execute(
        "CREATE INDEX ix_listing_title_trgm ON competitor_listing USING gin (title gin_trgm_ops)"
    )


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS ix_listing_title_trgm")
    op.execute("DROP INDEX IF EXISTS ix_listing_embedding_hnsw")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_observation_org_time", table_name="price_observation")
    op.drop_index("ix_observation_listing_time", table_name="price_observation")
    op.drop_table("price_observation")
    op.drop_index("ix_match_candidate_listing_score", table_name="match_candidate")
    op.drop_table("match_candidate")
    op.drop_index("ix_sales_fact_product_date", table_name="sales_fact")
    op.drop_index("ix_sales_fact_org_date", table_name="sales_fact")
    op.drop_table("sales_fact")
    op.drop_index("ix_recommendation_product_created", table_name="price_recommendation")
    op.drop_index("ix_recommendation_org_status", table_name="price_recommendation")
    op.drop_table("price_recommendation")
    op.drop_table("ground_truth")
    op.drop_index("ix_forecast_product_date", table_name="forecast_point")
    op.drop_table("forecast_point")
    op.drop_index("ix_elasticity_product_created", table_name="elasticity_estimate")
    op.drop_table("elasticity_estimate")
    op.drop_table("cross_elasticity")
    op.drop_index("ix_cost_history_product_date", table_name="cost_history")
    op.drop_table("cost_history")
    op.drop_index("ix_listing_matched_product", table_name="competitor_listing")
    op.drop_index("ix_listing_match_status", table_name="competitor_listing")
    op.drop_index(op.f("ix_competitor_listing_gtin"), table_name="competitor_listing")
    op.drop_table("competitor_listing")
    op.drop_index("ix_alert_org_status_created", table_name="alert")
    op.drop_index(op.f("ix_alert_dedupe_key"), table_name="alert")
    op.drop_table("alert")
    op.drop_index("ix_simulation_org_created", table_name="simulation_run")
    op.drop_table("simulation_run")
    op.drop_index(op.f("ix_product_sku"), table_name="product")
    op.drop_index("ix_product_org_category", table_name="product")
    op.drop_index(op.f("ix_product_gtin"), table_name="product")
    op.drop_table("product")
    op.drop_table("financial_metric")
    op.drop_index("ix_line_item_statement", table_name="financial_line_item")
    op.drop_table("financial_line_item")
    op.drop_index("ix_finding_period_severity", table_name="financial_finding")
    op.drop_table("financial_finding")
    op.drop_index("ix_audit_org_created", table_name="audit_event")
    op.drop_index("ix_audit_entity", table_name="audit_event")
    op.drop_table("audit_event")
    op.drop_index("ix_advisor_org_created", table_name="advisor_report")
    op.drop_table("advisor_report")
    op.drop_index("ix_model_run_kind_created", table_name="model_run")
    op.drop_table("model_run")
    op.drop_index("ix_financial_period_org_start", table_name="financial_period")
    op.drop_table("financial_period")
    op.drop_table("competitor")
    op.drop_table("category")
    op.drop_index(op.f("ix_app_user_email"), table_name="app_user")
    op.drop_table("app_user")
    op.drop_table("organization")
    # ### end Alembic commands ###
